//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarcLogic.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Attachment
    {
        public tb_Attachment()
        {
            this.tb_ProcessAttachment = new HashSet<tb_ProcessAttachment>();
        }
    
        public int AttachmentId { get; set; }
        public string Name { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.Guid CreateUserId { get; set; }
        public System.DateTime AlterDate { get; set; }
        public System.Guid AlterUserID { get; set; }
    
        public virtual ICollection<tb_ProcessAttachment> tb_ProcessAttachment { get; set; }
    }
}
