//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarcLogic.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Calendar
    {
        public int CalendarId { get; set; }
        public System.DateTime CDate { get; set; }
        public string Observation { get; set; }
        public bool Checked { get; set; }
        public string AssignedUser { get; set; }
        public System.DateTime CloseDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime AlterDate { get; set; }
        public string AlterUser { get; set; }
    }
}
