//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarcLogic.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Delegate
    {
        public tb_Delegate()
        {
            this.tb_ProcessDelegate = new HashSet<tb_ProcessDelegate>();
        }
    
        public int DelegateId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string MPhone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> CreateUserId { get; set; }
        public Nullable<System.DateTime> AlterDate { get; set; }
        public Nullable<System.Guid> AlterUserId { get; set; }
    
        public virtual ICollection<tb_ProcessDelegate> tb_ProcessDelegate { get; set; }
    }
}
