//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarcLogic.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Employer
    {
        public tb_Employer()
        {
            this.tb_ProcessEmployer = new HashSet<tb_ProcessEmployer>();
            this.tb_ProcessPayment = new HashSet<tb_ProcessPayment>();
        }
    
        public int EmployerdId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.Guid CreateUserId { get; set; }
        public System.DateTime AlterDate { get; set; }
        public System.Guid AlterUserId { get; set; }
    
        public virtual ICollection<tb_ProcessEmployer> tb_ProcessEmployer { get; set; }
        public virtual ICollection<tb_ProcessPayment> tb_ProcessPayment { get; set; }
    }
}
