//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarcLogic.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Entity
    {
        public tb_Entity()
        {
            this.tb_ProcessG = new HashSet<tb_ProcessG>();
        }
    
        public int EntityId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string IdentityCard { get; set; }
        public string HPhone { get; set; }
        public string MPhone { get; set; }
        public string ContactName { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public bool Active { get; set; }
        public string TaxNumber { get; set; }
        public string EAddress { get; set; }
        public string PostalCode { get; set; }
        public string Observation { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime AlterDate { get; set; }
        public string AlterUser { get; set; }
    
        public virtual ICollection<tb_ProcessG> tb_ProcessG { get; set; }
    }
}
