//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarcLogic.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Executed
    {
        public tb_Executed()
        {
            this.tb_ExecutedAddresses = new HashSet<tb_ExecutedAddresses>();
            this.tb_ProcessEmployer = new HashSet<tb_ProcessEmployer>();
            this.tb_ProcessSearch = new HashSet<tb_ProcessSearch>();
            this.tb_ProcessAttachment = new HashSet<tb_ProcessAttachment>();
            this.tb_Provision = new HashSet<tb_Provision>();
            this.tb_ProcessPayment = new HashSet<tb_ProcessPayment>();
        }
    
        public int ExecutedId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string IdentityCard { get; set; }
        public string NifNipl { get; set; }
        public string Nifs { get; set; }
        public Nullable<System.DateTime> BornDate { get; set; }
        public int Active { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.Guid CreateUserId { get; set; }
        public System.DateTime AlterDate { get; set; }
        public System.Guid AlterUserId { get; set; }
        public string MPhone { get; set; }
    
        public virtual ICollection<tb_ExecutedAddresses> tb_ExecutedAddresses { get; set; }
        public virtual ICollection<tb_ProcessEmployer> tb_ProcessEmployer { get; set; }
        public virtual ICollection<tb_ProcessSearch> tb_ProcessSearch { get; set; }
        public virtual ICollection<tb_ProcessAttachment> tb_ProcessAttachment { get; set; }
        public virtual ICollection<tb_Provision> tb_Provision { get; set; }
        public virtual ICollection<tb_ProcessPayment> tb_ProcessPayment { get; set; }
    }
}
