//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarcLogic.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ProvisionRequest
    {
        public int ProcessId { get; set; }
        public Nullable<System.DateTime> ProvisionRequest1 { get; set; }
        public Nullable<System.DateTime> ProvisionRequest2 { get; set; }
        public Nullable<System.DateTime> ProvisionRequest3 { get; set; }
        public Nullable<System.DateTime> ProvisionReinforcement1 { get; set; }
        public Nullable<System.DateTime> ProvisionReinforcement2 { get; set; }
        public Nullable<System.DateTime> ProvisionReinforcement3 { get; set; }
    
        public virtual tb_Process tb_Process { get; set; }
    }
}
