//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarcLogic.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PaymentType
    {
        public tb_PaymentType()
        {
            this.tb_ProcessPayment = new HashSet<tb_ProcessPayment>();
        }
    
        public int PaymentTypeId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<tb_ProcessPayment> tb_ProcessPayment { get; set; }
    }
}
