//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarcLogic.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ProcessClient
    {
        public int ProcessId { get; set; }
        public System.Guid ClientUserId { get; set; }
        public bool flag { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual tb_Process tb_Process { get; set; }
    }
}
