//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarcLogic.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ProcessFile
    {
        public int ProcessId { get; set; }
        public string Name { get; set; }
        public string SecureName { get; set; }
        public int UserPermission { get; set; }
        public int RepresentativePermission { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.Guid CreateUserId { get; set; }
        public System.DateTime AlterDate { get; set; }
        public System.Guid AlterUserId { get; set; }
        public short Id { get; set; }
    
        public virtual tb_Process tb_Process { get; set; }
    }
}
