//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarcLogic.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ProcessGPayment
    {
        public int ProcessGId { get; set; }
        public int PaymentId { get; set; }
        public string Designation { get; set; }
        public decimal Value { get; set; }
        public bool Income { get; set; }
        public System.DateTime PayDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime AlterDate { get; set; }
        public string AlterUser { get; set; }
    
        public virtual tb_ProcessG tb_ProcessG { get; set; }
    }
}
