//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarcLogic.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Process
    {
        public tb_Process()
        {
            this.tb_ExecutedAddresses = new HashSet<tb_ExecutedAddresses>();
            this.tb_ProcessRepresentativeInformation = new HashSet<tb_ProcessRepresentativeInformation>();
            this.tb_ProcessEmployer = new HashSet<tb_ProcessEmployer>();
            this.tb_ProcessSearch = new HashSet<tb_ProcessSearch>();
            this.tb_ProcessDelegate = new HashSet<tb_ProcessDelegate>();
            this.tb_ProcessAttachment = new HashSet<tb_ProcessAttachment>();
            this.tb_ProcessFile = new HashSet<tb_ProcessFile>();
            this.tb_Provision = new HashSet<tb_Provision>();
            this.tb_ProcessPayment = new HashSet<tb_ProcessPayment>();
            this.tb_ProcessClient = new HashSet<tb_ProcessClient>();
        }
    
        public int ProcessId { get; set; }
        public string Code { get; set; }
        public int Number { get; set; }
        public string Initials { get; set; }
        public int Year { get; set; }
        public string ProcessNumber { get; set; }
        public Nullable<float> Value { get; set; }
        public Nullable<float> ExesAE { get; set; }
        public string Classification { get; set; }
        public string Observation { get; set; }
        public Nullable<int> CourtId { get; set; }
        public Nullable<int> SectionId { get; set; }
        public Nullable<int> RepresentativeId { get; set; }
        public string Enforcement { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.Guid CreateUserID { get; set; }
        public System.DateTime AlterDate { get; set; }
        public System.Guid AlterUserId { get; set; }
        public Nullable<System.DateTime> AlterDate1 { get; set; }
        public Nullable<System.Guid> AlterUserId1 { get; set; }
        public Nullable<System.DateTime> AlterDate2 { get; set; }
        public Nullable<System.Guid> AlterUserId2 { get; set; }
        public Nullable<int> Section { get; set; }
        public string Localization { get; set; }
        public Nullable<int> ExecutionTypeId { get; set; }
        public string LocalizationDetail { get; set; }
        public string Alt { get; set; }
        public Nullable<int> LocalizationId { get; set; }
        public string CreatePCInfo { get; set; }
        public string AlterPCInfo { get; set; }
        public string AlterPCInfo1 { get; set; }
        public string AlterPCInfo2 { get; set; }
        public System.DateTime IRS { get; set; }
    
        public virtual tb_Court tb_Court { get; set; }
        public virtual ICollection<tb_ExecutedAddresses> tb_ExecutedAddresses { get; set; }
        public virtual tb_ExecutionType tb_ExecutionType { get; set; }
        public virtual tb_Localization tb_Localization { get; set; }
        public virtual tb_Payment tb_Payment { get; set; }
        public virtual tb_ProcessDetail tb_ProcessDetail { get; set; }
        public virtual ICollection<tb_ProcessRepresentativeInformation> tb_ProcessRepresentativeInformation { get; set; }
        public virtual ICollection<tb_ProcessEmployer> tb_ProcessEmployer { get; set; }
        public virtual ICollection<tb_ProcessSearch> tb_ProcessSearch { get; set; }
        public virtual ICollection<tb_ProcessDelegate> tb_ProcessDelegate { get; set; }
        public virtual ICollection<tb_ProcessAttachment> tb_ProcessAttachment { get; set; }
        public virtual ICollection<tb_ProcessFile> tb_ProcessFile { get; set; }
        public virtual tb_Representative tb_Representative { get; set; }
        public virtual tb_Section tb_Section { get; set; }
        public virtual tb_ProvisionRequest tb_ProvisionRequest { get; set; }
        public virtual ICollection<tb_Provision> tb_Provision { get; set; }
        public virtual ICollection<tb_ProcessPayment> tb_ProcessPayment { get; set; }
        public virtual ICollection<tb_ProcessClient> tb_ProcessClient { get; set; }
    }
}
