//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarcLogic.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ProcessPayment
    {
        public int PaymentYear { get; set; }
        public int PaymentId { get; set; }
        public int ProcessId { get; set; }
        public Nullable<int> ExecutedId { get; set; }
        public decimal OutCome { get; set; }
        public decimal InCome { get; set; }
        public decimal Vat { get; set; }
        public decimal RetentionValue { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public Nullable<int> RepresentativeId { get; set; }
        public Nullable<int> EmployerId { get; set; }
        public int Status { get; set; }
        public string InvoiceNumber { get; set; }
        public string Observation { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.Guid CreateUserId { get; set; }
        public System.DateTime AlterDate { get; set; }
        public System.Guid AlterUserId { get; set; }
    
        public virtual tb_Employer tb_Employer { get; set; }
        public virtual tb_Executed tb_Executed { get; set; }
        public virtual tb_PaymentType tb_PaymentType { get; set; }
        public virtual tb_Representative tb_Representative { get; set; }
        public virtual tb_Process tb_Process { get; set; }
    }
}
