//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarcLogic.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ProcessG
    {
        public tb_ProcessG()
        {
            this.tb_ProcessGHistory = new HashSet<tb_ProcessGHistory>();
            this.tb_ProcessGInformation = new HashSet<tb_ProcessGInformation>();
            this.tb_ProcessGPayment = new HashSet<tb_ProcessGPayment>();
        }
    
        public int ProcessGId { get; set; }
        public string Code { get; set; }
        public int EntityId { get; set; }
        public bool Closed { get; set; }
        public string Reference { get; set; }
        public string Observation { get; set; }
        public string Localization { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime AlterDate { get; set; }
        public string AlterUser { get; set; }
        public System.DateTime DateAlert { get; set; }
    
        public virtual tb_Entity tb_Entity { get; set; }
        public virtual ICollection<tb_ProcessGHistory> tb_ProcessGHistory { get; set; }
        public virtual ICollection<tb_ProcessGInformation> tb_ProcessGInformation { get; set; }
        public virtual ICollection<tb_ProcessGPayment> tb_ProcessGPayment { get; set; }
    }
}
