//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarcLogic.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ProcessDetail
    {
        public int ProcessId { get; set; }
        public Nullable<int> PaymentAgreementId { get; set; }
        public Nullable<int> ProcessExtinctionId { get; set; }
        public Nullable<int> ExtinctionCodeId { get; set; }
        public Nullable<int> ArrangementsInPlaceId { get; set; }
        public Nullable<int> InAttachmentId { get; set; }
        public Nullable<int> ProcessStateId { get; set; }
        public Nullable<int> DBInfoId { get; set; }
        public Nullable<int> UncollectabilityCertificateId { get; set; }
        public Nullable<decimal> Provision { get; set; }
        public Nullable<System.DateTime> ProvisionReceptionDate { get; set; }
        public Nullable<decimal> PendingInvoicePayment { get; set; }
        public string DiligenceLocation { get; set; }
        public Nullable<int> JudicialPhaseId { get; set; }
        public Nullable<System.DateTime> PendingInvoicePaymentDate { get; set; }
        public string CreditorReference { get; set; }
        public Nullable<System.DateTime> AcceptDate { get; set; }
        public Nullable<System.DateTime> DuplicatesReceipt { get; set; }
        public string JudgeObservation { get; set; }
        public int Alert { get; set; }
    
        public virtual tb_ArrangementsInPlace tb_ArrangementsInPlace { get; set; }
        public virtual tb_DBInfo tb_DBInfo { get; set; }
        public virtual tb_ExtinctionCode tb_ExtinctionCode { get; set; }
        public virtual tb_ProcessExtinction tb_ProcessExtinction { get; set; }
        public virtual tb_ProcessState tb_ProcessState { get; set; }
        public virtual tb_UncollectabilityCertificate tb_UncollectabilityCertificate { get; set; }
        public virtual tb_Process tb_Process { get; set; }
    }
}
