//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarcLogic.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Representative
    {
        public tb_Representative()
        {
            this.tb_ProcessPayment = new HashSet<tb_ProcessPayment>();
            this.tb_ProcessRepresentativeInformation = new HashSet<tb_ProcessRepresentativeInformation>();
            this.tb_Process = new HashSet<tb_Process>();
        }
    
        public int RepresentativeId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public Nullable<System.Guid> Userid { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.Guid CreateUserId { get; set; }
        public System.DateTime AlterDate { get; set; }
        public System.Guid AlterUserId { get; set; }
        public string Nif { get; set; }
        public string CarbonCopy { get; set; }
        public string MPhone { get; set; }
        public string LawyerNumber { get; set; }
    
        public virtual ICollection<tb_ProcessPayment> tb_ProcessPayment { get; set; }
        public virtual ICollection<tb_ProcessRepresentativeInformation> tb_ProcessRepresentativeInformation { get; set; }
        public virtual ICollection<tb_Process> tb_Process { get; set; }
    }
}
