//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarcLogic.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Search
    {
        public tb_Search()
        {
            this.tb_ProcessSearch = new HashSet<tb_ProcessSearch>();
        }
    
        public int SearchId { get; set; }
        public string Name { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.Guid CreateUserId { get; set; }
        public System.DateTime AlterDate { get; set; }
        public System.Guid AlterUserId { get; set; }
    
        public virtual ICollection<tb_ProcessSearch> tb_ProcessSearch { get; set; }
    }
}
